language: python
sudo: false
os: linux
dist: trusty
group: deprecated-2017Q3

cache: pip

services:
 - docker

env:
  global:
    - KUBECONFIG=${HOME}/.kube/kubernaut
    - SCOUT_DISABLE=1

install:
 - scripts/setup.sh
 - pip3 install kubernaut
 - kubernaut set-token $KUBERNAUT_TOKEN
 - pip install -r dev-requirements.txt
 - pip install -r requirements.txt
 - scripts/build.sh

before_script:
 - kubernaut claim
 - scripts/istio.sh

script:
 - scripts/test.sh

after_script:
 - kubernaut discard
